# Tokenizer Explorer

This notebook explores how different tokenizers convert text into tokens and token IDs.

We will:
- Count characters
- Count words
- Estimate token count
- Generate actual token IDs
- Decode token IDs back into text
- Compare GPT, WordPiece, and SentencePiece tokenization
- Test English, Marathi, Hindi, code, JSON, and emoji

In [11]:
print("Tokenizer Explorer is working!")

Tokenizer Explorer is working!

In [12]:
import tiktoken

In [13]:
encoding = tiktoken.get_encoding("o200k_base")

In [14]:
text_a = "hello world" #stores your sentence.
tokens_a = encoding.encode(text_a) #Take this human-readable text and convert it into token IDs
print("text: ",text_a)
print("token ids: ",tokens_a)
print("token count: ", len(tokens_a))

text:  hello world
token ids:  [24912, 2375]
token count:  2

In [15]:
text = "my name is radha"
tokens = encoding.encode(text)
print("text: ",text)
print("token ids: ",tokens)
print("token count: ", len(tokens))

text:  my name is radha
token ids:  [3825, 1308, 382, 9920, 1716]
token count:  5

In [16]:
decoded_text = encoding.decode(tokens_a)

print("og text: ", text_a)
print('token ids: ', tokens_a)
print("decoded text: ",decoded_text)

og text:  hello world
token ids:  [24912, 2375]
decoded text:  hello world

In [17]:
decode_text = encoding.decode(tokens)
print('original text: ', text)
print('after giving only tokens it will give the original text')
print('tokens: ',tokens)
print('decoded text: ',decode_text)

original text:  my name is radha
after giving only tokens it will give the original text
tokens:  [3825, 1308, 382, 9920, 1716]
decoded text:  my name is radha

In [18]:
if decode_text == text:
    print('decode successful!')
else:
    print('decode failed')

decode successful!

In [19]:
def analyze_text(text_b):
    character_count = len(text_b)
    word_count = len(text_b.split())
    token_ids = encoding.encode(text_b)
    token_count = len(token_ids)
    estimated_token_count = round(character_count/4,2)
    
    print('text',text_b)
    print()
    print('character count: ',character_count)
    print('word count: ',word_count)
    print('etc: ', estimated_token_count)
    print('actual token count: ', token_count)

In [20]:
text_b = "ESP32 autofocus failed due to SPI timeout."

analyze_text(text_b)

text ESP32 autofocus failed due to SPI timeout.

character count:  42
word count:  7
etc:  10.5
actual token count:  9

In [21]:
def show_tokens(text):
    token_ids = encoding.encode(text)
    
    for position,token_id in enumerate(token_ids):
        token_bytes = encoding.decode_single_token_bytes(token_id)
        
    try:
        token_text = token_bytes.decode('utf-8')
    except unicodedecodeerror:
        token_text = str(token_bytes)
        
    print(
        f" position: {position:2} | "
        f"Token ID: {token_id:6} | "
        f"Token: {repr(token_text)}"
    )

In [22]:
text =  "ESP32 autofocus failed due to SPI timeout."
show_tokens(text)

 position:  8 | Token ID:     13 | Token: '.'

In [23]:
token_ids = encoding.encode(text)

print("Number of tokens:", len(token_ids))
print("Token IDs:", token_ids)

Number of tokens: 9
Token IDs: [78336, 1398, 112947, 9363, 5192, 316, 48776, 20451, 13]

In [24]:
for position, token_id in enumerate(token_ids):
    token_bytes = encoding.decode_single_token_bytes(token_id)
    
    try:
        token_text = token_bytes.decode("utf-8")
    except UnicodeDecodeError:
        token_text = str(token_bytes)
    
    print(f"{position}: {repr(token_text)}")

0: 'ESP'
1: '32'
2: ' autofocus'
3: ' failed'
4: ' due'
5: ' to'
6: ' SPI'
7: ' timeout'
8: '.'

In [25]:
import pandas as pd

In [26]:
def token_table(text):
    token_ids = encoding.encode(text)

    rows = []

    for position, token_id in enumerate(token_ids):
        token_bytes = encoding.decode_single_token_bytes(token_id)

        try:
            token_text = token_bytes.decode("utf-8")
        except UnicodeDecodeError:
            token_text = str(token_bytes)

        rows.append({
            "Position": position,
            "Token ID": token_id,
            "Token": token_text
        })

    return pd.DataFrame(rows)

In [27]:
text = "ESP32 autofocus failed due to SPI timeout."

token_table(text)

   Position  Token ID       Token
0         0     78336         ESP
1         1      1398          32
2         2    112947   autofocus
3         3      9363      failed
4         4      5192         due
5         5       316          to
6         6     48776         SPI
7         7     20451     timeout
8         8        13           .

In [28]:
token_ids = encoding.encode(text)
decoded_text = encoding.decode(token_ids)

print('original: ',text)
print('decoded text: ',decoded_text)

print('same text: ', text == decoded_text)

original:  ESP32 autofocus failed due to SPI timeout.
decoded text:  ESP32 autofocus failed due to SPI timeout.
same text:  True

In [29]:
examples = {
    "English": "The autofocus system failed because the SPI communication timed out.",
    
    "Marathi": "ऑटोफोकस सिस्टम SPI टाइमआउटमुळे अयशस्वी झाली.",
    
    "Hindi": "ऑटोफोकस सिस्टम SPI टाइमआउट के कारण विफल हो गई।",
    
    "Code": """def autofocus(camera):
    if spi_timeout:
        return False
    return True""",
    
    "JSON": """{
    "device": "ESP32",
    "status": "failed",
    "error": "SPI timeout"
}""",
    
    "Emoji": "🚀 🔥 ❤️ 🤖 😊"
}

print("Number of examples:", len(examples))

Number of examples: 6

In [30]:
token_table(examples["English"])

    Position  Token ID           Token
0          0       976             The
1          1    112947       autofocus
2          2      2420          system
3          3      9363          failed
4          4      2236         because
5          5       290             the
6          6     48776             SPI
7          7     11686   communication
8          8     53414           timed
9          9       842             out
10        10        13               .

In [31]:
token_table(examples["Marathi"])

    Position  Token ID    Token
0          0    107138        ऑ
1          1    175625       टो
2          2      8944        फ
3          3     23325       ोक
4          4      1496        स
5          5    161596   सिस्टम
6          6     48776      SPI
7          7    177215     टाइम
8          8     14417        आ
9          9     16636        उ
10        10      3330        ट
11        11      1637        म
12        12     99914      ुळे
13        13      2473        अ
14        14      2762        य
15        15      4003        श
16        16     53168      स्व
17        17       840        ी
18        18    169235     झाली
19        19        13        .

In [32]:
token_table(examples["Hindi"])

    Position  Token ID                                 Token
0          0    107138                                     ऑ
1          1    175625                                    टो
2          2      8944                                     फ
3          3     23325                                    ोक
4          4      1496                                     स
5          5    161596                                सिस्टम
6          6     48776                                   SPI
7          7    177215                                  टाइम
8          8     14417                                     आ
9          9     16636                                     उ
10        10      3330                                     ट
11        11      2329                                    के
12        12     32062                                  कारण
13        13      8228  b' \xe0\xa4\xb5\xe0\xa4\xbf\xe0\xa4'
14        14       104                               b'\xab'
15        15      1455                                     ल
16        16      5492                                    हो
17        17     26403                                    गई
18        18      1670                                     ।

In [33]:
token_table(examples["JSON"])

    Position  Token ID     Token
0          0       745       {\n
1          1       271
2          2       392         "
3          3     12404    device
4          4      1243        ":
5          5       392         "
6          6     78336       ESP
7          7      1398        32
8          8      1150      ",\n
9          9       271
10        10       392         "
11        11      6063    status
12        12      1243        ":
13        13       392         "
14        14     33814    failed
15        15      1150      ",\n
16        16       271
17        17       392         "
18        18      1544     error
19        19      1243        ":
20        20       392         "
21        21     92588       SPI
22        22     20451   timeout
23        23      1092       "\n
24        24        92         }

# Experiment: GPT vs SentencePiece vs WordPiece

We use the exact same sentence with three different tokenizers:

> ESP32 autofocus failed due to SPI timeout.

The goal is to compare how each tokenizer splits the same text and how many tokens are produced.

In [34]:
sentence = 'esp32 autofocus succeded with spi'
print(sentence)

esp32 autofocus succeded with spi

In [35]:
gpt_token_ids = encoding.encode(sentence)

print('gpt token ids: ',gpt_token_ids)
print('gpt token count: ', len(gpt_token_ids))

gpt token ids:  [18342, 1398, 112947, 16915, 93687, 483, 70297]
gpt token count:  7

In [36]:
gpt_tokens = []

for token_id in gpt_token_ids:
    token_bytes = encoding.decode_single_token_bytes(token_id)
    
    try:
        token_text = token_bytes.decode("utf-8")
    except UnicodeDecodeError:
        token_text = str(token_bytes)
    
    gpt_tokens.append(token_text)

print(gpt_tokens)

['esp', '32', ' autofocus', ' succ', 'eded', ' with', ' spi']

In [37]:
from transformers import AutoTokenizer

In [38]:
sp_tokenizer = AutoTokenizer.from_pretrained("google/mt5-small")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [39]:
x = sp_tokenizer(sentence, add_special_tokens = False)
 
sp_token_ids = x['input_ids']
print('sentence token ids: ', sp_token_ids)

print('sentencepiece token count: ',len(sp_token_ids))

sentence token ids:  [22005, 3322, 1864, 23714, 75427, 285, 345, 514, 57540]
sentencepiece token count:  9

In [40]:
sp_tokens = sp_tokenizer.convert_ids_to_tokens(sp_token_ids)

print("SentencePiece Tokens:")
print(sp_tokens)

SentencePiece Tokens:
['▁esp', '32', '▁auto', 'focus', '▁succe', 'd', 'ed', '▁with', '▁spi']

In [41]:
sp_table = pd.DataFrame({
    "Position": range(len(sp_token_ids)),
    "Token ID": sp_token_ids,
    "Token": sp_tokens
})

sp_table

   Position  Token ID   Token
0         0     22005    ▁esp
1         1      3322      32
2         2      1864   ▁auto
3         3     23714   focus
4         4     75427  ▁succe
5         5       285       d
6         6       345      ed
7         7       514   ▁with
8         8     57540    ▁spi

In [42]:
sp_decoded = sp_tokenizer.decode(
    sp_token_ids,
    skip_special_tokens=True
)

print("Original:")
print(sentence)

print("\nDecoded:")
print(sp_decoded)

print("\nSame text:", sentence == sp_decoded)

Original:
esp32 autofocus succeded with spi

Decoded:
esp32 autofocus succeded with spi

Same text: True

In [43]:
from tokenizers import Tokenizer

In [44]:
wordpiece_tokenizer = Tokenizer.from_pretrained("bert-base-uncased")

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [49]:
wp_output = wordpiece_tokenizer.encode(sentence)

wp_token_ids = wp_output.ids
wp_tokens = wp_output.tokens

print("WordPiece Token IDs for sentence:")
print(wp_token_ids)

print("\nWordPiece Token Count :")
print(len(wp_token_ids))

print('the sentence is: ',sentence)

WordPiece Token IDs for sentence:
[101, 9686, 2361, 16703, 8285, 14876, 7874, 10514, 9468, 19082, 2007, 11867, 2072, 102]

WordPiece Token Count :
14
the sentence is:  esp32 autofocus succeded with spi

In [50]:
print("WordPiece Tokens:")
print(wp_tokens)

WordPiece Tokens:
['[CLS]', 'es', '##p', '##32', 'auto', '##fo', '##cus', 'su', '##cc', '##eded', 'with', 'sp', '##i', '[SEP]']

In [51]:
wp_table = pd.DataFrame({
    "Position": range(len(wp_token_ids)),
    "Token ID": wp_token_ids,
    "Token": wp_tokens
})

wp_table

    Position  Token ID   Token
0          0       101   [CLS]
1          1      9686      es
2          2      2361     ##p
3          3     16703    ##32
4          4      8285    auto
5          5     14876    ##fo
6          6      7874   ##cus
7          7     10514      su
8          8      9468    ##cc
9          9     19082  ##eded
10        10      2007    with
11        11     11867      sp
12        12      2072     ##i
13        13       102   [SEP]

In [52]:
wp_decoded = wordpiece_tokenizer.decode(wp_token_ids)

print("Original:")
print(sentence)

print("\nDecoded:")
print(wp_decoded)

print("\nSame text:", sentence.lower() == wp_decoded)

Original:
esp32 autofocus succeded with spi

Decoded:
esp32 autofocus succeded with spi

Same text: True

In [53]:
comparison = pd.DataFrame({
    "Tokenizer": [
        "GPT",
        "SentencePiece",
        "WordPiece"
    ],
    "Token Count": [
        len(gpt_token_ids),
        len(sp_token_ids),
        len(wp_token_ids)
    ]
})

comparison

       Tokenizer  Token Count
0            GPT            7
1  SentencePiece            9
2      WordPiece           14

In [54]:
token_comparison = pd.DataFrame({
    "GPT": pd.Series(gpt_tokens),
    "SentencePiece": pd.Series(sp_tokens),
    "WordPiece": pd.Series(wp_tokens)
})

token_comparison

           GPT SentencePiece WordPiece
0          esp          ▁esp     [CLS]
1           32            32        es
2    autofocus         ▁auto       ##p
3         succ         focus      ##32
4         eded        ▁succe      auto
5         with             d      ##fo
6          spi            ed     ##cus
7          NaN         ▁with        su
8          NaN          ▁spi      ##cc
9          NaN           NaN    ##eded
10         NaN           NaN      with
11         NaN           NaN        sp
12         NaN           NaN       ##i
13         NaN           NaN     [SEP]

# Observations

## 1. GPT tokenizer

GPT tokenization uses a BPE-based approach. The sentence is divided into subword pieces according to the tokenizer's vocabulary.

## 2. SentencePiece

The SentencePiece-based tokenizer represents the sentence using its own learned vocabulary and segmentation strategy. Word boundaries may be represented using a special marker such as `▁`.

## 3. WordPiece

WordPiece can split words into smaller subword pieces. Continuation pieces are commonly shown using the `##` prefix.

## 4. Token counts

The three tokenizers do not necessarily produce the same number of tokens for the same sentence. This happens because they use different vocabularies and tokenization strategies.

For this experiment:

- GPT produced [7] tokens.
- SentencePiece produced [9] tokens.
- WordPiece produced [14] tokens.

Therefore, the tokenizer with the lowest token count for this particular sentence was GPT.

This result should not be interpreted as meaning that this tokenizer will always produce fewer tokens. Token efficiency depends on the input text and the tokenizer's vocabulary.

## 5. Important conclusion

A token is not necessarily the same thing as a word.

The same word can be represented as one token by one tokenizer and multiple subword tokens by another tokenizer.

Therefore, token count is tokenizer-dependent.